// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function IsCertInstalled() {
  return window['go']['main']['App']['IsCertInstalled']();
}

export function LaunchTrae(arg1, arg2) {
  return window['go']['main']['App']['LaunchTrae'](arg1, arg2);
}

export function SelectTraePath() {
  return window['go']['main']['App']['SelectTraePath']();
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UninstallCert() {
  return window['go']['main']['App']['UninstallCert']();
}
