// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportKeysToFile(arg1) {
  return window['go']['main']['App']['ExportKeysToFile'](arg1);
}

export function GetMachineID() {
  return window['go']['main']['App']['GetMachineID']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportKeysFromFile() {
  return window['go']['main']['App']['ImportKeysFromFile']();
}

export function InstallCert() {
  return window['go']['main']['App']['InstallCert']();
}

export function IsCertInstalled() {
  return window['go']['main']['App']['IsCertInstalled']();
}

export function LaunchTrae(arg1, arg2) {
  return window['go']['main']['App']['LaunchTrae'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SelectTraePath() {
  return window['go']['main']['App']['SelectTraePath']();
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UninstallCert() {
  return window['go']['main']['App']['UninstallCert']();
}

export function UpdateKeyPool(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateKeyPool'](arg1, arg2, arg3);
}

export function UpdateModelMap(arg1, arg2) {
  return window['go']['main']['App']['UpdateModelMap'](arg1, arg2);
}

export function UpdateSystemPrompt(arg1, arg2) {
  return window['go']['main']['App']['UpdateSystemPrompt'](arg1, arg2);
}
