// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachineID():Promise<string>;

export function InstallCert():Promise<void>;

export function IsCertInstalled():Promise<boolean>;

export function LaunchTrae(arg1:string,arg2:number):Promise<void>;

export function SelectTraePath():Promise<string>;

export function StartProxy(arg1:number,arg2:string,arg3:string):Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCert():Promise<void>;
