// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportKeysToFile(arg1:string):Promise<void>;

export function GetMachineID():Promise<string>;

export function GetPlatform():Promise<string>;

export function HideWindow():Promise<void>;

export function ImportKeysFromFile():Promise<string>;

export function InstallCert():Promise<void>;

export function IsCertInstalled():Promise<boolean>;

export function LaunchTrae(arg1:string,arg2:number):Promise<void>;

export function QuitApp():Promise<void>;

export function SelectTraePath():Promise<string>;

export function StartProxy(arg1:number,arg2:string,arg3:string):Promise<void>;

export function StopProxy():Promise<void>;

export function UninstallCert():Promise<void>;

export function UpdateKeyPool(arg1:Array<string>,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function UpdateModelMap(arg1:Record<string, string>,arg2:Record<string, string>):Promise<void>;

export function UpdateSystemPrompt(arg1:boolean,arg2:string):Promise<void>;
